services:
  backend:
    profiles: [all]
    build: ./backend
    container_name: backend
    environment:
      APP_ROOT: /var/www/html/public
      MERCURE_URL: http://sse-server:3000/.well-known/mercure
      MERCURE_PUBLIC_URL: http://localhost:3000/.well-known/mercure
      MERCURE_PUBLISHER_JWT_KEY: '${MERCURE_JWT_PUBLISHER_SECRET}'
      DATABASE_URL: mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@database:3306/${DATABASE_NAME}?serverVersion=mariadb-${MARIADB_VERSION}&charset=utf8mb4
      TEST_DATABASE_URL: mysql://root:rootpassword@database:3306/test_db?serverVersion=mariadb-${MARIADB_VERSION}&charset=utf8mb4
    volumes:
      - ../backend:/var/www/html
      - ./backend/php-xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ../frontend/build:/var/www/html/public/frontend
      #- ./backend/apache-site.conf:/etc/apache2/sites-enabled/00-default.conf
    ports:
      - "${BACKEND_PORT}:80"
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  sse-server:
    profiles: [all]
    image: dunglas/mercure
    container_name: sse-server
    restart: unless-stopped
    environment:
      SERVER_NAME: ':3000'
      MERCURE_PUBLISHER_JWT_KEY: '${MERCURE_JWT_PUBLISHER_SECRET}'
      MERCURE_SUBSCRIBER_JWT_KEY: '${MERCURE_JWT_SUBSCRIBER_SECRET}'
      MERCURE_PUBLISHER_JWT_ALG: 'HS256'
      MERCURE_SUBSCRIBER_JWT_ALG: 'HS256'
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins http://localhost:5173 http://localhost:${BACKEND_PORT}
        anonymous
    ports:
      - '3000:3000'
    networks:
      - app-network

  database:
    profiles: [all]
    image: mariadb:${MARIADB_VERSION}
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

  frontend:
    profiles: [all]
    image: node:25
    container_name: frontend
    working_dir: /app
    volumes:
      - ../frontend:/app
    environment:
      VITE_MERCURE_URL: http://localhost:3000/.well-known/mercure
      VITE_API_URL: http://localhost:${BACKEND_PORT}
      VITE_MERCURE_JWT_SUBSCRIBER_TOKEN: '${MERCURE_JWT_SUBSCRIBER_TOKEN}'
    ports:
      - "5173:5173"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mariadb_data:

