services:
  backend:
    profiles: [all]
    build: ./backend
    container_name: backend
    environment:
      APP_ROOT: /var/www/html/public
      DATABASE_URL: mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@database:3306/${DATABASE_NAME}?serverVersion=mariadb-${MARIADB_VERSION}&charset=utf8mb4
      TEST_DATABASE_URL: mysql://root:rootpassword@database:3306/test_db?serverVersion=mariadb-${MARIADB_VERSION}&charset=utf8mb4
    volumes:
      - ../backend:/var/www/html
    ports:
      - "${BACKEND_PORT}:80"
    networks:
      - app-network

  database:
    profiles: [all]
    image: mariadb:${MARIADB_VERSION}
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      VITE_MERCURE_URL: http://mercure:3000/mercure
      VITE_API_URL: http://localhost:${BACKEND_PORT}/api
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

  frontend:
    profiles: [all]
    image: node:25
    container_name: frontend
    working_dir: /app
    volumes:
      - ../frontend:/app
    ports:
      - "5173:5173"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mariadb_data:

